services:
  frontend:
    container_name: react-frontend
    build:
      context: ./frontend
    develop:
      # live reloading of container
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
          ignore:
            - node_modules/
        # need to rebuild when we install new packages
        - action: rebuild
          path: package.json
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    container_name: dotnet-backend
    build:
      context: ./backend
    # env data found in .env.dev
    env_file: ./.env
    develop:
      # live reloading, dotnet does watching, see ./backend/Dockerfile line 17
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - node_modules/
            - obj/
            - bin/
        # rebuild with new packages
        - action: rebuild
          path: package.json
    depends_on:
      - db
      - keycloak
    ports:
      - "5269:5269"

  db:
    container_name: postgres-db
    build:
      context: ./db
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.7
    container_name: keycloak
    environment:
      # Database Config (Quarkus format)
      KC_DB: postgres
      KC_DB_URL: "${KC_DB_URL}"
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: "${KC_DB_PASSWORD}"
      # Allows http://keycloak:8080 from other containers
      KC_HOSTNAME_STRICT: "false"
      # Disables strict HTTPS enforcement for now
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "${KC_BOOTSTRAP_ADMIN_PASSWORD}"
      KC_BOOTSTRAP_ADMIN_USERNAME: "${KC_BOOTSTRAP_ADMIN_USERNAME}"
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - keycloak_data:/opt/keycloak/data
      # Mount local json files to the container's import folder
      - ./react-realm-realm.json:/opt/keycloak/data/import/react-realm-realm.json
      # m

volumes:
  pgdata:
  keycloak_data:
